---
# TODO(sshnaidm): to ansibilize this playbook
- name: Local setup for quickstart
  hosts: localhost
  connection: local
  tasks:
    - name: Host setup
      shell: >
        sudo hostnamectl set-hostname undercloud;
        echo 'undercloud' | sudo dd of=/etc/hostname;
        echo "127.0.0.1 $(hostname) $(hostname).openstacklocal" | sudo tee -a /etc/hosts;
        echo "127.0.0.2 undercloud undercloud.openstacklocal" | sudo tee -a /etc/hosts;
        if [ ! -e ${HOME}/.ssh/id_rsa.pub ] ; then
            if [[ -e ${HOME}/.ssh/id_rsa ]]; then
                ssh-keygen -y -f ${HOME}/.ssh/id_rsa > ${HOME}/.ssh/id_rsa.pub;
            else
                ssh-keygen -N "" -f ${HOME}/.ssh/id_rsa;
            fi
        fi;
        cat ~/.ssh/id_rsa.pub | sudo tee -a /root/.ssh/authorized_keys | tee -a ~/.ssh/authorized_keys;

        sudo yum remove -y puppet hiera puppetlabs-release rdo-release;
        sudo rm -rf /etc/puppet /etc/hiera.yaml;
        sudo cp {{tripleo_root}}/tripleo-ci/test-environments/overcloud-cacert.pem /etc/pki/ca-trust/source/anchors/;
        sudo update-ca-trust extract;
        cp -f {{ lookup('env', 'TE_DATAFILE') }} ~/instackenv.json;
        {{tripleo_root}}/tripleo-ci/scripts/tripleo.sh --repo-setup;
        sudo yum reinstall -y python-requests || sudo yum install -y python-requests;
        sudo yum install -y python-tripleoclient libguestfs-xfs libguestfs-tools-c;
  tags:
    - local

# TODO(sshnaidm): to move this to settings(?)
- name: Prepare environment for quickstart
  hosts: undercloud
  gather_facts: no
  tasks:
    - name: Here comes any undercloud setup which is required for quickstart to run
      debug: msg="Here comes any setup which is required for quickstart to run"

    - name: Add hiera overriding file
      template:
        src: "{{tripleo_root}}/tripleo-ci/scripts/quickstart/quickstart-hieradata-overrides.yaml.j2"
        dest: ~/quickstart-hieradata-overrides.yaml

# TODO(sshnaidm): fix role for proper handle of skipped projects
- name: Run DLRN gate role and create repo
  hosts: undercloud
  vars:
    artg_compressed_gating_repo: "/home/jenkins/gating_repo.tar.gz"
    ansible_user: jenkins
    ansible_user_dir: /home/jenkins/
    artg_skipped_projects:
        - openstack/tripleo-quickstart
        - openstack-infra/tripleo-ci
  roles:
    - { role: build-test-packages, when: "{{ lookup('env', 'USE_DELOREAN')|default(0, true) }} == 1" }

# TODO(sshnaidm): to create a separate role for this in quickstart-extras(?)
- include: inject_repo-playbook.yml
