---
# TODO(sshnaidm): to ansibilize this playbook
- name: Local setup for quickstart
  hosts: localhost
  connection: local
  tasks:
    - name: Host setup
      shell: >
        sudo hostnamectl set-hostname undercloud;
        echo 'undercloud' | sudo dd of=/etc/hostname;
        echo "127.0.0.1 $(hostname) $(hostname).openstacklocal" | sudo tee -a /etc/hosts;
        echo "127.0.0.2 undercloud undercloud.openstacklocal" | sudo tee -a /etc/hosts;
        if [ ! -e ${HOME}/.ssh/id_rsa.pub ] ; then
            if [[ -e ${HOME}/.ssh/id_rsa ]]; then
                ssh-keygen -y -f ${HOME}/.ssh/id_rsa > ${HOME}/.ssh/id_rsa.pub;
            else
                ssh-keygen -N "" -f ${HOME}/.ssh/id_rsa;
            fi
        fi;
        cat ~/.ssh/id_rsa.pub | sudo tee -a /root/.ssh/authorized_keys | tee -a ~/.ssh/authorized_keys;

        sudo yum remove -y puppet hiera puppetlabs-release rdo-release;
        sudo rm -rf /etc/puppet /etc/hiera.yaml;
        sudo cp {{tripleo_root}}/tripleo-ci/test-environments/overcloud-cacert.pem /etc/pki/ca-trust/source/anchors/;
        sudo update-ca-trust extract;
        cp -f {{ lookup('env', 'TE_DATAFILE') }} ~/instackenv.json;
        {{tripleo_root}}/tripleo-ci/scripts/tripleo.sh --repo-setup;
        sudo yum reinstall -y python-requests || sudo yum install -y python-requests;
        sudo yum install -y python-tripleoclient libguestfs-xfs libguestfs-tools-c;
  tags:
    - local

# TODO(sshnaidm): to move this to settings(?)
- name: Prepare environment for quickstart
  hosts: undercloud
  gather_facts: no
  tasks:
    - name: Here comes any undercloud setup which is required for quickstart to run
      debug: msg="Here comes any setup which is required for quickstart to run"

    - name: Add hiera overriding file
      template:
        src: "{{tripleo_root}}/tripleo-ci/scripts/quickstart/quickstart-hieradata-overrides.yaml.j2"
        dest: ~/quickstart-hieradata-overrides.yaml

- name: Get images for quickstart
  hosts: undercloud
  gather_facts: no
  tasks:
    - name: Prepare images
      shell: >
        source {{tripleo_root}}/tripleo-ci/scripts/common_functions.sh;
        prepare_images_oooq
      when: "not '{{ lookup('env', 'STABLE_RELEASE') }}'"
