---
- name: Run overcloud prep config
  hosts: undercloud
  gather_facts: no
  roles:
    - role: overcloud-prep-config
      # only run when we know we have to, save time otherwise
      when: mixed_upgrade|default(false)|bool
  tags:
    - overcloud-prep-config

- name: Run overcloud prep roles
  hosts: undercloud
  gather_facts: no
  roles:
    - { role: overcloud-prep-images, step_overcloud_image: false, step_glance_upload: true, step_register: false }

- name: Run tripleo-validations pre-introspection tests
  hosts: undercloud
  gather_facts: no
  tags:
    - tripleo-validations
  vars:
    validations_group: ['pre-introspection']
  roles:
    - { role: tripleo-validations,
        when: run_tripleo_validations|bool or run_tripleo_validations_negative_tests|bool}

- name: Prepare for containerized deployment
  hosts: undercloud
  gather_facts: no
  tags:
    - overcloud-prep-containers
  roles:
    - role: overcloud-prep-containers
      when: containerized_overcloud|bool or containerized_overcloud_upgrade|bool

- name: Run tripleo-validations pre-deployment tests
  hosts: undercloud
  gather_facts: no
  tags:
    - tripleo-validations
  vars:
    validations_group: ['pre-deployment']
  roles:
    - { role: tripleo-validations,
        when: run_tripleo_validations|bool or run_tripleo_validations_negative_tests|bool}
