undercloud: undercloud
environment_infra: ovb
playbooks: |
  {% if featureset == '001' %}
  [
    "baremetal-full-deploy.yml"
  ]
  {% else %}
  [
    "ovb-setup.yml",
    "baremetal-full-undercloud.yml",
    "baremetal-full-overcloud-prep.yml",
    "baremetal-full-overcloud.yml",
    "baremetal-full-overcloud-validate.yml"
  ]
  {% endif %}
