---
- hosts:
    - primary
    - centos-7
  name: Autoconverted job from tripleo legacy jobs
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - name: zuul-cloner
      shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              https://opendev.org \
              openstack/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
      changed_when: true

    - name: run safe-devstack-vm-gate-wrap.sh
      shell:
        cmd: |
          set -e
          set -x
          export TOCI_JOBTYPE={{ toci_jobtype }}
          export DISTRIBUTION={{ ansible_distribution }}
          export DISTRIBUTION_MAJOR_VERSION={{ ansible_distribution_major_version }}

          # ZUUL does not set these for periodic jobs
          export ZUUL_BRANCH=${ZUUL_BRANCH:-master}
          export ZUUL_REF=${ZUUL_REF:-None}

          # Compatibility with zuul v3 variables
          export JOB_NAME={{ zuul.job }}
          export LOG_PATH={{ zuul.change[-2:] }}/{{ zuul.change }}/{{ zuul.patchset }}/{{ zuul.pipeline }}/{{ zuul.job }}/{{ zuul.build[:7] }}

          export BRANCH_OVERRIDE="{{ branch_override | default('default') }}"
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_HORIZON=1
          export PROJECTS="openstack/tripleo-quickstart $PROJECTS"
          export PROJECTS="openstack/tripleo-quickstart-extras $PROJECTS"
          export PROJECTS="openstack/tripleo-upgrade $PROJECTS"

          sudo chown -hR $(whoami) /opt/git
          function gate_hook {
              bash -xe /opt/stack/new/tripleo-ci/toci_gate_test.sh
          }
          export -f gate_hook
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
      changed_when: true
