---
# Collect logs settings

# artcl_tar_gz: true
artcl_gzip_only: true
artcl_txt_rename: true
artcl_publish: true
artcl_rsync_logs: false
artcl_collect_list:
  - /var/lib/container-puppet/
  - /var/lib/config-data/puppet-generated/
  - /var/lib/docker-puppet/
  - /var/lib/heat-config/
  - /var/lib/kolla/config_files/
  - /var/lib/mistral/
  - /var/lib/neutron/
  - /var/lib/tripleo-config/
  - /var/lib/unbound/unbound.log
  - /var/lib/certmonger/
  - /home/{{ undercloud_user }}/.instack/install-undercloud.log
  - /home/{{ undercloud_user }}/.config/openstack/
  - /home/{{ undercloud_user }}/stackrc
  - /home/{{ undercloud_user }}/overcloudrc
  - /home/*/*.log
  - /home/*/*.txt
  - /home/*/*.json
  - /home/*/*.conf
  - /home/*/*.cfg
  - /home/*/*.y*ml*
  - /home/*/*.sh
  - /home/*/undercloud-ansible-*
  - /home/{{ undercloud_user }}/deploy-overcloudrc
  - /home/{{ undercloud_user }}/network-environment.yaml
  - /home/{{ undercloud_user }}/workspace/ovb/*.y*ml
  - /home/{{ undercloud_user }}/skip_file
  - /home/{{ undercloud_user }}/*.subunit
  - /home/{{ undercloud_user }}/tempest/
  - /home/{{ undercloud_user }}/tripleo-heat-installer-templates/
  - /home/{{ undercloud_user }}/local_tht/
  - /home/{{ undercloud_user }}/inventory
  - /home/{{ undercloud_user }}/tripleo-config-download/
  - /home/{{ undercloud_user }}/tripleo-*-config/
  - /home/{{ undercloud_user }}/tripleo-config/
  - /home/{{ undercloud_user }}/*-ansible-*/
  - /home/{{ undercloud_user }}/*-install-*
  - /home/{{ undercloud_user }}/browbeat/log/*
  - /home/{{ undercloud_user }}/.config/
  - /home/{{ undercloud_user }}/.tobiko/
  - /tmp/ansible-*/
  - /tmp/ansible-*
  - /etc/ansible/
  - /etc/aodh/
  - /etc/autofs*
  - /etc/auto.master*
  - /etc/barbican/
  - /etc/ceilometer/
  - /etc/centos-release*
  - /etc/ceph/
  - /etc/chrony.conf
  - /etc/ci/
  - /etc/cinder/
  - /etc/cloud/
  - /etc/collectd.conf*
  - /etc/collectd.d/
  - /etc/congress/
  - /etc/containers/
  - /etc/corosync/
  - /etc/default/
  - /etc/dib-*/
  - /etc/dib-*
  - /etc/dnsmasq*
  - /etc/docker/
  - /etc/docker-distribution/
  - /etc/ec2api/
  - /etc/etcd/
  - /etc/exports*
  - /etc/exports*/
  - /etc/facter/
  - /etc/firewalld/
  - /etc/fluentd/
  - /etc/fstab
  - /etc/glance/
  - /etc/gnocchi/
  - /etc/group*
  - /etc/ha.d/
  - /etc/haproxy/
  - /etc/heat/
  - /etc/hiera.*
  - /etc/host.conf
  - /etc/hostname
  - /etc/hosts
  - /etc/httpd/conf*/
  - /etc/idmapd.conf
  - /etc/image-hostname
  - /etc/ipa/
  - /etc/iproute2/
  - /etc/ironic/
  - /etc/ironic-inspector/
  - /etc/iscsi/
  - /etc/keepalived/
  - /etc/keystone/
  - /etc/kolla/
  - /etc/krb5.conf*
  - /etc/krb5.conf*/
  - /etc/kubernetes/
  - /etc/libvirt/
  - /etc/lsb-release.d/
  - /etc/lvm/
  - /etc/machine-id
  - /etc/manila/
  - /etc/mistral/
  - /etc/modprobe.d/
  - /etc/modules-load.d/
  - /etc/mongo*
  - /etc/my.cnf*
  - /etc/my.cnf.d/
  - /etc/named*
  - /etc/named/
  - /etc/NetworkManager/
  - /etc/networks*
  - /etc/neutron/
  - /etc/nodepool/
  - /etc/nova*
  - /etc/nova*/
  - /etc/nsswitch.conf*
  - /etc/ntp/
  - /etc/ntp.conf
  - /etc/numad.conf
  - /etc/oci-register-machine.conf
  - /etc/octavia/
  - /etc/openldap/
  - /etc/openstack/
  - /etc/openstack-dashboard/
  - /etc/openvswitch/
  - /etc/origin/
  - /etc/os-*
  - /etc/os-net-config/
  - /etc/pacemaker/
  - /etc/panko/
  - /etc/pip.conf
  - /etc/pki/
  - /etc/polkit-1/
  - /etc/protocols*
  - /etc/puppet/
  - /etc/pycadf/
  - /etc/python/
  - /etc/qemu-kvm/
  - /etc/qpid-dispatch/
  - /etc/rabbitmq/
  - /etc/radvd.conf
  - /etc/redhat-lsb/
  - /etc/redhat-release*
  - /etc/redis*
  - /etc/redis*/
  - /etc/resolv.*
  - /etc/rootwrap.d/
  - /etc/rsyncd.conf
  - /etc/rsyslog.*
  - /etc/rsyslog.d/
  - /etc/ryu/
  - /etc/sahara/
  - /etc/sasl2/
  - /etc/security/
  - /etc/selinux/config
  - /etc/sensu/
  - /etc/sestatus.conf
  - /etc/shadow*
  - /etc/snmp/
  - /etc/skydive/
  - /etc/sos.conf
  - /etc/ssl/
  - /etc/ssh/
  - /etc/sssd/
  - /etc/sudo.conf
  - /etc/sudoers*
  - /etc/sudoers.d/
  - /etc/swift/
  - /etc/sysconfig/
  - /etc/sysctl.*
  - /etc/sysctl.d/
  - /etc/systemd/*.conf
  - /etc/systemd/system/ceph*
  - /etc/tacker/
  - /etc/target/
  - /etc/tempest/
  - /etc/trove/
  - /etc/trusted-*
  - /etc/tuna/
  - /etc/unbound/unbound.conf
  - /etc/unbound/forwarding.conf
  - /etc/unbound/conf.d/ttl.conf
  - /etc/unbound/conf.d/unbound-logging.conf
  - /etc/vconsole.conf
  - /etc/yum/
  - /etc/dnf/
  - /etc/yum.conf
  - /etc/yum.repos.d/
  - /etc/zaqar/
  - /var/log/atop*
  - /var/log/dmesg.txt
  - /var/log/host_info.txt
  - /var/log/journal.txt
  - /var/log/postci.txt
  - /var/log/secure
  - /var/log/unbound.log
  - /var/log/yum.log
  - /var/log/dnf.log
  - /var/log/cloud-init*.log
  - /var/log/aodh/
  - /var/log/audit/
  - /var/log/barbican/
  - /var/log/ceilometer/
  - /var/log/ceph/
  - /var/log/cinder/
  - /var/log/cloudkitty/
  - /var/log/cluster/
  - /var/log/config-data/
  - /var/log/congress/
  - /var/log/containers/
  - /var/log/deployed-server-enable-ssh-admin.log
  - /var/log/deployed-server-os-collect-config.log
  - /var/log/designate/
  - /var/log/dirsrv/
  - /var/log/dmesg/
  - /var/log/extra/
  - /var/log/ec2api/
  - /var/log/glance/
  - /var/log/gnocchi/
  - /var/log/heat/
  - /var/log/heat-launcher/
  - /var/log/horizon/
  - /var/log/httpd/
  - /var/log/ipaclient-install.log
  - /var/log/ironic/
  - /var/log/ironic-inspector/
  - /var/log/krb5*.log
  - /var/log/libvirt/
  - /var/log/keystone/
  - /var/log/manila/
  - /var/log/mariadb/
  - /var/log/mistral/
  - /var/log/monasca/
  - /var/log/murano/
  - /var/log/neutron/
  - /var/log/nova/
  - /var/log/novajoin/
  - /var/log/octavia/
  - /var/log/openvswitch/
  - /var/log/ovn/
  - /var/log/os-apply-config.log
  - /var/log/pacemaker/
  - /var/log/pacemaker.log*
  - /var/log/panko/
  - /var/log/paunch.log
  - /var/log/pcsd/
  - /var/log/pki/
  - /var/log/qdr/
  - /var/log/rabbitmq/
  - /var/log/redis/
  - /var/log/sahara/
  - /var/log/sensu/
  - /var/log/setup-ipa-client.log
  - /var/log/setup-ipa-client-ansible.log
  - /var/log/sssd/
  - /var/log/swift/
  - /var/log/tacker/
  - /var/log/tempest/
  - /var/log/tripleo-container-image-prepare.log
  - /var/log/trove/
  - /var/log/vitrage/
  - /var/log/watcher/
  - /var/log/zaqar/
  - /var/named/

# the above list was created from
# https://raw.githubusercontent.com/openstack/puppet-openstack-integration/master/openstack_modules.txt
artcl_exclude_list:
  - /etc/puppet/modules/
  - /var/log/journal/*
  - /var/log/extra/lsof*
  - /home/{{ undercloud_user }}/tempest/etc/cirros*
  - /home/{{ undercloud_user }}/tempest/.stackviz
  - /home/{{ undercloud_user }}/tempest/.stestr
  - /home/{{ undercloud_user }}/tempest/etc/*.sample
  - /home/{{ undercloud_user }}/.tobiko/cache/
  - /home/{{ undercloud_user }}/instackenv.json
  - /etc/pki/rhui/
